# Generated by Django 2.2.5 on 2019-09-10 09:32

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190910_0914'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
